trace:
  endpoint: http://127.0.0.1:14268/api/traces
server:
  http:
    addr: 0.0.0.0:0
    timeout: 1s
  grpc:
    addr: 0.0.0.0:0
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:dangerous@tcp(127.0.0.1:3306)/test?parseTime=true
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
