apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml -o ../kubernetes
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: web-shop
  name: web-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web-shop
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml -o ../kubernetes
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: web-shop
    spec:
      containers:
        - image: go-kratos/beer-web-shop:0.1.0
          name: web-shop
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
